### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by tidesnetwork** [keefertaylor/TezosKit#1]
Great work on the library. I am wondering if you have plans for supporting OSX and when.

Thanks

**Comment by keefertaylor** [comment]
Hi!

Definitely want to support OSX. This should actually build for OSX now. 

It's unfortunate that to make a podspec you can only depend on libraries in the CocoaPods respository and you can't depend on pods on Github.

One of my dependencies, CKMnemonic doesn't declare OSX support and the project doesn't appear to be maintained. I don't readily see any other mnemonic libraries in CocoaPods that are swift friendly.  I am considering forking their project and creating my own pod as I don't like their API anyway. MnemonicUtil is essentially a facade for a mnemonic library, so it should be pretty easy to replace.

In general, I have a lot of pain with CocoaPods' approach to dependency management so I'm trying to get my library into their repo ASAP so other's don't have this issue. Right now that looks like: 
- Adding tests for the library
- Declaring tests in the podspec
- Administrivia to get it uploaded

After that is when I'd have a chance to start looking at fixing my dependencies and OSX support. How urgent is your request?

**Comment by keefertaylor** [comment]
Turns out writing new code is more fun than writing tests. I've started writing a fork of CKMnemonic (called MnemonicKit obvi) here: https://github.com/keefertaylor/MnemonicKit

Once that library gets pushed into the CocoaPods trunk it should be trival to enable OSX compatibility for this library.

**Comment by keefertaylor** [comment]
I think that this commit will have fixed the issue for you: [Add support for OSX](https://github.com/keefertaylor/TezosKit/commit/a69dc9fc0e1c855fd99252fc9680d48636915e6d) 

Feel free to re-open this issue if you have any problems building. If you end up building something on TezosKit, I'd love to see what you make. Drop me a line if you make anything :)

**Comment by tidesnetwork** [comment]
Hi again, I am getting the following error when I tried installing the pod.

> [!] Unable to find a specification for `MnemonicKit` depended upon by `TezosKit`

**Comment by tidesnetwork** [comment]
That fixed it thanks.
