### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by simonmcl** [keefertaylor/TezosKit#181]
A lot of the errors come back as "TransactionFormationErrors". When debugging code that is in progress having some simple logging (with the option to turn on/off) to see whats coming back from the network would be very useful.

I find myself adding the below to the NetworkClient while debugging to be able to see errors, without spamming the console.

```
if rpc is RunOperationRPC || rpc is PreapplyOperationRPC {
    print("\n\n\ndataString: \( String(data: data!, encoding: .utf8) ) \n\n\n")
}
```

**Comment by keefertaylor** [comment]
Fixed in #186.
