### ISSUE TITLE
Sending Tezos

### ISSUE THREAD

**Issue by fortmarek** [keefertaylor/TezosKit#3]
Hey,
First thanks for this library!

I wanted to know if you checked if sending tezos works, I have tried, but the completion closure is never called. 

Do you have any idea why?

**Comment by keefertaylor** [comment]
Hi! Thanks for using my library. 

I am still working on getting test coverage up, but AFAIK everything should be working.

I tried this just now and it works fine for me. If you want to provide some code (obviously make sure to strip out secret keys, etc) I can try to take a look at it and figure out what's wrong. 

Here's some code I tested just now:
```
let wallet = Wallet(mnemonic: [redacted], passphrase: [redacted])!
print(wallet.address)

let wallet2 = Wallet(mnemonic: [redacted], passphrase: [redacted])!
print(wallet2.address)

 let t = TezosClient()
 let b = TezosBalance(balance: "1")!
 t.send(amount: b, to: wallet2.address, from: wallet.address, keys: wallet.keys) { (txHash, err) in
     print("Sent! \(txHash), \(err)")
 }
```

**Comment by fortmarek** [comment]
Yeah, probably a mistake somewhere on my part, sorry!

**Comment by keefertaylor** [comment]
Interestingly, in poking around tonight I discovered that there was a bug in TezosBalances if you were initializing with whole numbers and using the decimal based initializer rather than the string (Issue #4). Maybe that had to do with this error?

**Comment by keefertaylor** [comment]
Awesome!

I’ve stamped the library as 1.0 as of this morning, in that I’m fairly confident it’s fully featured for the use case of a wallet. 

You may want to rebase to head. In addition to the TezosBalance fix, there’s an originateOperation which lets you originate new contracts. Right now it is focused on delegation so they account is just empty, but you just need to add a ‘script’ param to the payload.  

Good luck on the smart contract stuff! If you’re able to get it working, we can consider merging it back here (assuming you’re open to it, of course).

Feel free to reach out if you have questions on the above or need help working with the library (or if you just have feedback). My email is on my personal site or you can open issues.
